---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    - access_key: ""
      secret_key: ""
      key_pair_name: ""
      vm_region: ""
      vm_volume_size: ""

  tasks:
    - name: Create a new AWS EC2 instance
      ec2:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        image: ami-0653e888ec96eab9b
        instance_type: t3.small
        key_name: "{{ key_pair_name }}"
        region: "{{ vm_region }}"
        state: present
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: "{{ vm_volume_size }}"
        wait: true
        wait_timeout: 400
      register: ec2_vm

    - name: Add the new VM IP address to the hosts file in `servers' group
      add_host:
        name: "{{ ec2_vm.instances[0].public_ip }}"
        groups: ec2instances

    - name: Wait for SSH connection
      wait_for:
        host: "{{ ec2_vm.instances[0].public_ip }}"
        port: 22
        state: started

- hosts: ec2instances
  remote_user: ubuntu
  become: true
  gather_facts: false
  pre_tasks:
    - name: Install python
      raw: "apt install -y python"

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Install PHP 7.0
      apt:
        name: php7.0
        state: present

    - name: Install Apache PHP module
      apt:
        name: libapache2-mod-php7.0
        state: present

    - name: Install PHP 7.0 CLI
      apt:
        name: php7.0-cli
        state: present

    - name: Install PHP 7.0 Common API
      apt:
        name: php7.0-common
        state: present

    - name: Install PHP 7.0 MBString library
      apt:
        name: php7.0-mbstring
        state: present

    - name: Install PHP 7.0 GD library
      apt:
        name: php7.0-gd
        state: present

    - name: Install PHP 7.0 INTL library
      apt:
        name: php7.0-intl
        state: present

    - name: Install PHP 7.0 XML
      apt:
        name: php7.0-xml
        state: present

    - name: Install PHP 7.0 MySQL library
      apt:
        name: php7.0-mysql
        state: present

    - name: Install PHP 7.0 MCrypt library
      apt:
        name: php7.0-mcrypt
        state: present

    - name: Install PHP 7.0 Zip library
      apt:
        name: php7.0-zip
        state: present

    - name: Install MariaDB server package
      apt:
        name: mariadb-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started

    - name: Install Python MySQL package
      apt:
        name: python-mysqldb
        state: present

    - name: Install MySQL extension for PHP
      apt:
        name: php7.0-mysql
        state: present

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
