---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    - access_key: ""
      secret_key: ""
      key_pair_name: ""
      vm_region: ""
      vm_volume_size: ""

  tasks:
    - name: Create a new AWS EC2 instance
      ec2:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        image: ami-0653e888ec96eab9b
        instance_type: t3.small
        key_name: "{{ key_pair_name }}"
        region: "{{ vm_region }}"
        state: present
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: "{{ vm_volume_size }}"
        wait: true
        wait_timeout: 400
      register: ec2_vm

    - name: Add the new VM IP address to the hosts file in `servers' group
      add_host:
        name: "{{ ec2_vm.instances[0].public_ip }}"
        groups: servers

    - name: Wait for SSH connection
      wait_for:
        host: "{{ ec2_vm.instances[0].public_ip }}"
        port: 22
        state: started

- hosts: servers
  remote_user: ubuntu
  become: true
  gather_facts: false
  pre_tasks:
    - name: Install python
      raw: "sudo apt install -y python"

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
    - service:
        name: apache2
        state: started
        enabled: true
