---
- hosts: localhost
  connection: local
  gather_facts: "no"

  vars:
    - access_key: ""
      secret_key: ""
      key_pair_name: ""
      vm_region: ""
      vm_volume_size: ""

  tasks:
    - name: Create a new AWS EC2 instance
      ec2:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        image: ami-0653e888ec96eab9b
        instance_type: t3.small
        key_name: "{{ key_pair_name }}"
        region: "{{ vm_region }}"
        state: present
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: "{{ vm_volume_size }}"
        wait: "yes"
        wait_timeout: 400
